// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  modsSidebar: [
    {
      type: 'category',
      label: 'My Mods',
      link: {type: 'doc', id: 'mods/index'},
      items: [
        "mods/torcherino",
        "mods/travel-staff",
        "mods/entity-rain",
        "mods/find-my-friends",
        "mods/simple-xp-config",
        "mods/mercenaries",
        "mods/tiered-shulkers",
        "mods/inclusive-enchanting",
        "mods/mountables",
        "mods/tribes",
        "mods/harder-core",
      ],
    },
  ],
  postsSidebar: [
    {type: 'autogenerated', dirName: 'posts'}
  ],
  gistsSidebar: [
    {type: 'autogenerated', dirName: 'mirror'}
  ],
  tutorialSidebar: [
    "intro",
    "java-basics",
    "concepts",
    {
      type: 'category',
      label: '1.16.5',
      items: [{type: 'autogenerated', dirName: '1.16.5'}],
    },
    {
      type: 'category',
      label: '1.18.2',
      items: [{type: 'autogenerated', dirName: '1.18.2'}],
    },
    {
      type: 'category',
      label: '1.19.2',
      items: [{type: 'autogenerated', dirName: '1.19.2'}],
    },
    "mixins",
    "dependencies",
    {
      type: 'category',
      label: 'WrapperLib',
      link: {type: "doc", id: "wrapperlib/index"},
      items: [
        {type: "doc", id: "wrapperlib/installation", label: "Installation"},
        {type: "doc", id: "wrapperlib/serialization", label: "Serialization"},
        {type: "doc", id: "wrapperlib/networking", label: "Networking"},
        {type: "doc", id: "wrapperlib/config", label: "Config"},
        {type: "doc", id: "wrapperlib/keybinds", label: "Key Bindings"},
        {type: "doc", id: "wrapperlib/saved-data", label: "Saved Data"},
        {type: "doc", id: "wrapperlib/resources", label: "Resources"},
      ],
    },
    "publishing",
    "solutions",
    "other-tutorials"
  ],
};

module.exports = sidebars;
